USE simuladorFinal;

CREATE TABLE SIMULADOR (
    ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    SIMULACAO_FINALIZADA BOOLEAN DEFAULT FALSE,
    TIPO_SIMULACAO VARCHAR(10),
    PRIMARY KEY(ID),
    INDEX (ID)  -- Adicionando índice à coluna ID
);

CREATE TABLE POSICAO_ITERACAO (
    ID INT AUTO_INCREMENT,
    SIMULADOR_ID INTEGER UNSIGNED NOT NULL,
    POSICAO INT,
    PRIMARY KEY(ID),
	INDEX (SIMULADOR_ID),
    FOREIGN KEY (SIMULADOR_ID) REFERENCES SIMULADOR(ID)
);

CREATE TABLE TABELA_PRINCIPAL (
    ID INT NOT NULL AUTO_INCREMENT,
    REF1 INT,
    REF2 INT,
    REF3 INT,
    REF4 INT,
    COLUNAS_CINZAS VARCHAR(200),
    SIMULADOR_ID INTEGER UNSIGNED NOT NULL,
    PRIMARY KEY(ID),
    INDEX (SIMULADOR_ID),
    FOREIGN KEY (SIMULADOR_ID) REFERENCES SIMULADOR(ID)
);

CREATE TABLE RESULTADOS (
    ID INT NOT NULL AUTO_INCREMENT,
    TOTAL INT,
    POSICAO INT,
    TABELA_PRINCIPAL_ID INT NOT NULL,
    PRIMARY KEY(ID),
    INDEX (TABELA_PRINCIPAL_ID),
    FOREIGN KEY (TABELA_PRINCIPAL_ID) REFERENCES TABELA_PRINCIPAL(ID)
);
