use simuladorFinal;

CREATE TABLE SIMULADOR (  
    ID integer unsigned not null auto_increment,
    NOME varchar(100) not null,
    SIMULACAO_FINALIZADA bool default False,
    TIPO_SIMULACAO varchar(10),
    PRIMARY KEY(ID)
);

CREATE TABLE TABELA_PRINCIPAL (
    ID INT NOT NULL AUTO_INCREMENT,
    REF1 INT,
    REF2 INT,
    REF3 INT,
    REF4 INT,
    COLUNAS_CINZAS varchar(200),
    SIMULADOR_ID integer unsigned not null,
    PRIMARY KEY(ID),
    INDEX (SIMULADOR_ID),
    FOREIGN KEY (SIMULADOR_ID)
    REFERENCES SIMULADOR(id)
);

CREATE TABLE RESULTADOS (
    ID INT NOT NULL AUTO_INCREMENT,
    TOTAL INT,
    POSICAO INT,
    TABELA_PRINCIPAL_ID INT NOT NULL,
    PRIMARY KEY(ID),
    INDEX (TABELA_PRINCIPAL_ID),
    FOREIGN KEY (TABELA_PRINCIPAL_ID)
    REFERENCES TABELA_PRINCIPAL(id)
);